//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan_Uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarih
    {
        public int tarihid { get; set; }
        public string tarih1 { get; set; }
    }
}
